### ISSUE TITLE
Fix location input in launch form

### ISSUE THREAD

**Issue by israellevin** [paket-core/web#11]
Currently, we have many location fields, including some that override each other - GPS location of... vs. Address of... We obviously can't have both. If we have an address input (the usual case) then you should resolve it into an address (talk to the guys, they are using the google places API with much success). Sometimes we may want to choose from a map, or maybe even enter GPS location, but in any event, the user must input only one alternative.

This is related to #10, of course.

**Comment by VitaliyKvas** [comment]
Now the address as a text field (with autocomplete). 
It's enough or need all three case ?

**Comment by israellevin** [comment]
This will absolutely do for now. Closing.
