### ISSUE TITLE
Do not expose private key

### ISSUE THREAD

**Issue by israellevin** [paket-core/web#6]
Private keys (and anything that generates private keys, like seeds and mnemonics) are highly sensitive data, and are not to be displayed on the screen (so no one can see them when looking behind your shoulder).

In our case, the correct thing to display instead of the private key is the public key, which is also the Stellar address.

So instead of `PrivateKey: SAGMKB4K5FB3K2WJ4GCMLJJE5UUVV45ZF7IWKB53WO7LPBJD4CPEWU5J` we should see `Stellar address: xxx`.

**Comment by VitaliyKvas** [comment]
Now display instead of the private key is the public key
